# SPDX-FileCopyrightText: 2025 GSI Helmholtzzentrum für Schwerionenforschung GmbH <https://www.gsi.de/en/>
#
# SPDX-License-Identifier: CC0-1.0

version = 1

[[annotations]]
path = [
  ".gitignore",
  ".golangci.yml",
  "docs/reference.md"
]
SPDX-FileCopyrightText = "2025 GSI Helmholtzzentrum für Schwerionenforschung GmbH <https://www.gsi.de/en/>"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = [
  "cmd/bmctl/boot.go",
  "cmd/bmctl/main.go",
  "cmd/bmctl/version.go",
  "cmd/bmctl/version_test.go",
  "go.mod",
  "go.sum",
  "pkg/bmc/bmc.go",
  "pkg/bmc/client.go",
  "pkg/bmc/http.go",
  "pkg/bmc/http_test.go",
  "pkg/cli/errors.go",
  "pkg/cli/errors_test.go",
  "pkg/cli/execute.go",
  "pkg/cli/execute_test.go",
  "pkg/cli/signals.go",
  "pkg/cli/signals_test.go",
  "pkg/logging/context.go",
  "pkg/logging/context_test.go",
  "pkg/logging/logger.go",
  "pkg/ssh/proxy.go",
  "pkg/testing/capture.go",
  "pkg/testing/capture_test.go",
  "pkg/testing/fork.go",
  "pkg/testing/fork_test.go",
]
SPDX-FileCopyrightText = "2025 GSI Helmholtzzentrum für Schwerionenforschung GmbH <https://www.gsi.de/en/>"
SPDX-License-Identifier = "LGPL-3.0-or-later"
